"""Vendor and handcraft bot-detection signature banks."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, Pattern, Tuple


@dataclass(frozen=True)
class VendorSignature:
    name: str
    handcraft: bool = False
    headers: Tuple[str, ...] = ()
    header_prefixes: Tuple[str, ...] = ()
    header_values: Dict[str, Tuple[str, ...]] = field(default_factory=dict)
    cookies: Tuple[str, ...] = ()
    body_patterns: Tuple[str, ...] = ()
    script_patterns: Tuple[str, ...] = ()


def compile_patterns(patterns: Tuple[str, ...]) -> Tuple[Pattern[str], ...]:
    return tuple(re.compile(p, re.IGNORECASE) for p in patterns)


VENDORS: Tuple[VendorSignature, ...] = (
    VendorSignature(
        name="cloudfront_waf",
        headers=("x-amz-cf-id", "x-amz-cf-pop"),
        header_prefixes=("x-amz-cf-",),
        header_values={
            "server": ("cloudfront",),
            "x-cache": ("cloudfront", "error from cloudfront"),
        },
        body_patterns=(
            r"Generated by cloudfront",
            r"The request could not be satisfied",
            r"Request blocked",
            r"403 ERROR",
        ),
    ),
    VendorSignature(
        name="cloudflare",
        headers=("cf-ray", "cf-mitigated", "cf-cache-status"),
        header_values={"server": ("cloudflare",)},
        cookies=("__cf_bm", "cf_clearance"),
        body_patterns=(
            r"Just a moment",
            r"cdn-cgi/challenge-platform",
            r"__cf_chl_opt",
            r"Checking your browser before accessing",
        ),
        script_patterns=(r"/cdn-cgi/challenge-platform/", r"challenges\.cloudflare\.com"),
    ),
    VendorSignature(
        name="akamai",
        headers=("is-akamai-cdn",),
        header_prefixes=("x-akamai-",),
        cookies=("_abck", "bm_sz", "ak_bmsc", "bm_sv"),
        body_patterns=(r"akamai",),
        script_patterns=(r"/akam/", r"bmak\.js"),
    ),
    VendorSignature(
        name="imperva_incapsula",
        headers=("x-iinfo",),
        header_values={"x-cdn": ("incapsula", "imperva")},
        cookies=("incap_ses_", "visid_incap_", "nlbi_"),
        body_patterns=(r"Incapsula incident ID", r"_Incapsula_Resource"),
        script_patterns=(r"/_Incapsula_Resource",),
    ),
    VendorSignature(
        name="datadome",
        headers=("x-datadome", "x-dd-b", "x-datadome-cid"),
        cookies=("datadome",),
        body_patterns=(r"datadome", r"DataDome"),
        script_patterns=(r"/datadome/js/", r"datadome\.co"),
    ),
    VendorSignature(
        name="perimeterx_human",
        header_prefixes=("x-px-",),
        cookies=("_px3", "_pxvid", "_pxhd", "_pxde", "pxcts"),
        body_patterns=(r"perimeterx", r"Access to this page has been denied"),
        script_patterns=(r"px-cloud\.net", r"perimeterx\.net", r"/init\.js"),
    ),
    VendorSignature(
        name="kasada",
        header_prefixes=("x-kpsdk-",),
        cookies=("x-kpsdk-ct", "x-kpsdk-cd"),
        script_patterns=(r"/149e9513-", r"kasada\.io"),
    ),
    VendorSignature(
        name="h1base_botjs",
        handcraft=True,
        cookies=("bjt",),
        body_patterns=(
            r"data-cid\s*=",
            r"Checking your browser",
            r"Verifying your browser",
            r'meta\s+name\s*=\s*["\']robots["\']\s+content\s*=\s*["\'][^"\']*noindex',
            r"bjt-fail",
        ),
        script_patterns=(r"/botjs/verify", r"/botjs/captcha", r"/js/[A-Za-z0-9_-]+\.js"),
    ),
)

INTERSTITIAL_PATTERNS = compile_patterns((
    r"checking your browser",
    r"verifying you are human",
    r"just a moment",
    r"please wait while we verify",
    r"security check",
    r"javascript is required",
    r"enable javascript",
))

HONEYPOT_PATTERNS = compile_patterns((
    r'display\s*:\s*none[^>]*>\s*<a\s',
    r'visibility\s*:\s*hidden[^>]*>\s*<a\s',
    r'class\s*=\s*["\'][^"\']*honeypot',
    r'name\s*=\s*["\'][^"\']*(?:hp_|honeypot|bot_trap)',
    r'<a[^>]+href\s*=\s*["\'][^"\']*(?:/admin|/wp-admin|/xmlrpc|/crime_case)["\']',
))

IMMEDIATE_JS_PATTERNS = compile_patterns((
    r"/botjs/verify",
    r"/cdn-cgi/challenge-platform/",
    r"fetch\s*\(\s*['\"][^'\"]*(?:verify|challenge|sensor|collect)",
    r"navigator\.sendBeacon\s*\(",
    r"eval\s*\(\s*decodeURIComponent\s*\(\s*atob\s*\(",
))

LISTENER_JS_PATTERNS = compile_patterns((
    r"addEventListener\s*\(\s*['\"]mousemove",
    r"addEventListener\s*\(\s*['\"]keydown",
    r"addEventListener\s*\(\s*['\"]touchstart",
    r"addEventListener\s*\(\s*['\"]scroll",
    r"addEventListener\s*\(\s*['\"]wheel",
    r"addEventListener\s*\(\s*['\"]pointermove",
    r"onmousemove\s*=",
    r"onkeydown\s*=",
))

DEFERRED_JS_PATTERNS = compile_patterns((
    r"requestIdleCallback\s*\(",
    r"setTimeout\s*\(",
    r"MutationObserver\s*\(",
    r"IntersectionObserver\s*\(",
))

SIGNAL_JS_PATTERNS: Dict[str, Tuple[Pattern[str], ...]] = {
    "webdriver": compile_patterns((r"navigator\.webdriver",)),
    "automation_globals": compile_patterns((r"cdc_", r"__webdriver_", r"__selenium_", r"_phantom", r"domAutomation")),
    "toString_tamper": compile_patterns((r"\[native code\]", r"Function\.prototype\.toString")),
    "canvas": compile_patterns((r"toDataURL", r"HTMLCanvasElement")),
    "webgl_renderer": compile_patterns((r"WEBGL_debug_renderer_info", r"UNMASKED_RENDERER")),
    "audio": compile_patterns((r"OfflineAudioContext", r"webkitOfflineAudioContext")),
    "webrtc_stun": compile_patterns((r"RTCPeerConnection", r"stun:")),
    "hardware_concurrency": compile_patterns((r"hardwareConcurrency",)),
    "device_memory": compile_patterns((r"deviceMemory",)),
    "user_agent_data": compile_patterns((r"userAgentData",)),
    "fonts": compile_patterns((r"offsetWidth", r"mmmmmmmmmmlli")),
    "performance_now": compile_patterns((r"performance\.now\s*\(",)),
}

CAPTCHA_PATTERNS = compile_patterns((
    r"g-recaptcha",
    r"h-captcha",
    r"cf-turnstile",
    r"recaptcha/api",
    r"hcaptcha\.com",
    r"Click the (?:red|blue|yellow) (?:circle|square|triangle)",
    r"/botjs/captcha",
))

SCRIPT_SRC_RE = re.compile(r'<script[^>]+src\s*=\s*["\']([^"\']+)["\']', re.IGNORECASE)
INLINE_SCRIPT_RE = re.compile(
    r"<script(?![^>]*\bsrc\s*=)[^>]*>([\s\S]*?)</script>",
    re.IGNORECASE,
)

INTERSTITIAL_SHORT_BODY = 24_000
